--------------------------------------------------------
--  Fichier créé - jeudi-février-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOYE
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_EMPLOYE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOYES
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_EMPLOYES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EQUIPE
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_EQUIPE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EQUIPES
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_EQUIPES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MISSION
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_MISSION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MISSIONS
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_MISSIONS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POUBELLE
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_POUBELLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POUBELLES
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_POUBELLES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ZONE
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_ZONE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ZONES
--------------------------------------------------------

   CREATE SEQUENCE  "SAFWCARM"."SEQ_ZONES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SAFWCARM"."EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"POSTE" VARCHAR2(50 BYTE), 
	"DISPONIBILITE" VARCHAR2(30 BYTE), 
	"HEURES_TRAVAIL" NUMBER, 
	"SALAIRE" NUMBER(10,2), 
	"SEXE" VARCHAR2(10 BYTE), 
	"ID_EQUIPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPE
--------------------------------------------------------

  CREATE TABLE "SAFWCARM"."EQUIPE" 
   (	"ID_EQUIPE" NUMBER, 
	"NOM_EQUIPE" VARCHAR2(100 BYTE), 
	"ID_ZONE" NUMBER, 
	"CHEF_EQUIPE" VARCHAR2(100 BYTE), 
	"NOMBRE_MEMBRES" NUMBER, 
	"STATUT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSION
--------------------------------------------------------

  CREATE TABLE "SAFWCARM"."MISSION" 
   (	"ID_MISSION" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"DATE_MISSION" DATE, 
	"DUREE" NUMBER, 
	"ETAT" VARCHAR2(50 BYTE), 
	"PRIORITE" VARCHAR2(30 BYTE), 
	"ID_EQUIPE" NUMBER, 
	"ID_ZONE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POUBELLE
--------------------------------------------------------

  CREATE TABLE "SAFWCARM"."POUBELLE" 
   (	"ID_POUBELLE" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"CAPACITE_MAX" NUMBER, 
	"NIVEAU_REMPLISSAGE" NUMBER, 
	"ETAT" VARCHAR2(50 BYTE), 
	"LOCALISATION" VARCHAR2(100 BYTE), 
	"DATE_VIDANGE" DATE, 
	"ID_ZONE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ZONE
--------------------------------------------------------

  CREATE TABLE "SAFWCARM"."ZONE" 
   (	"ID_ZONE" NUMBER, 
	"NOM_ZONE" VARCHAR2(100 BYTE), 
	"TYPE_ZONE" VARCHAR2(50 BYTE), 
	"SUPERFICIE" NUMBER(10,2), 
	"POPULATION_ESTIMEE" NUMBER, 
	"PRIORITE_COLLECTE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SAFWCARM.EMPLOYE
SET DEFINE OFF;
REM INSERTING into SAFWCARM.EQUIPE
SET DEFINE OFF;
REM INSERTING into SAFWCARM.MISSION
SET DEFINE OFF;
REM INSERTING into SAFWCARM.POUBELLE
SET DEFINE OFF;
REM INSERTING into SAFWCARM.ZONE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger TRIG_EMPLOYE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SAFWCARM"."TRIG_EMPLOYE" 
BEFORE INSERT ON EMPLOYE
FOR EACH ROW
BEGIN
    SELECT SEQ_EMPLOYE.NEXTVAL
    INTO :NEW.ID_EMPLOYE
    FROM DUAL;
END;

/
ALTER TRIGGER "SAFWCARM"."TRIG_EMPLOYE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_EQUIPE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SAFWCARM"."TRIG_EQUIPE" 
BEFORE INSERT ON EQUIPE
FOR EACH ROW
BEGIN
    SELECT SEQ_EQUIPE.NEXTVAL
    INTO :NEW.ID_EQUIPE
    FROM DUAL;
END;

/
ALTER TRIGGER "SAFWCARM"."TRIG_EQUIPE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_MISSION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SAFWCARM"."TRIG_MISSION" 
BEFORE INSERT ON MISSION
FOR EACH ROW
BEGIN
    SELECT SEQ_MISSION.NEXTVAL
    INTO :NEW.ID_MISSION
    FROM DUAL;
END;

/
ALTER TRIGGER "SAFWCARM"."TRIG_MISSION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_POUBELLE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SAFWCARM"."TRIG_POUBELLE" 
BEFORE INSERT ON POUBELLE
FOR EACH ROW
BEGIN
    SELECT SEQ_POUBELLE.NEXTVAL
    INTO :NEW.ID_POUBELLE
    FROM DUAL;
END;

/
ALTER TRIGGER "SAFWCARM"."TRIG_POUBELLE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_ZONE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SAFWCARM"."TRIG_ZONE" 
BEFORE INSERT ON ZONE
FOR EACH ROW
BEGIN
    SELECT SEQ_ZONE.NEXTVAL
    INTO :NEW.ID_ZONE
    FROM DUAL;
END;

/
ALTER TRIGGER "SAFWCARM"."TRIG_ZONE" ENABLE;
--------------------------------------------------------
--  Constraints for Table ZONE
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."ZONE" ADD PRIMARY KEY ("ID_ZONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SAFWCARM"."ZONE" MODIFY ("NOM_ZONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MISSION
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."MISSION" ADD PRIMARY KEY ("ID_MISSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SAFWCARM"."MISSION" MODIFY ("ID_ZONE" NOT NULL ENABLE);
  ALTER TABLE "SAFWCARM"."MISSION" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."EMPLOYE" ADD PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SAFWCARM"."EMPLOYE" ADD CHECK (SEXE IN ('Homme','Femme')) ENABLE;
  ALTER TABLE "SAFWCARM"."EMPLOYE" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPE
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."EQUIPE" ADD PRIMARY KEY ("ID_EQUIPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SAFWCARM"."EQUIPE" MODIFY ("ID_ZONE" NOT NULL ENABLE);
  ALTER TABLE "SAFWCARM"."EQUIPE" MODIFY ("NOM_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POUBELLE
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."POUBELLE" ADD PRIMARY KEY ("ID_POUBELLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SAFWCARM"."POUBELLE" MODIFY ("ID_ZONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."EMPLOYE" ADD CONSTRAINT "FK_EMPLOYE_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "SAFWCARM"."EQUIPE" ("ID_EQUIPE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPE
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."EQUIPE" ADD CONSTRAINT "FK_EQUIPE_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "SAFWCARM"."ZONE" ("ID_ZONE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSION
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."MISSION" ADD CONSTRAINT "FK_MISSION_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "SAFWCARM"."EQUIPE" ("ID_EQUIPE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SAFWCARM"."MISSION" ADD CONSTRAINT "FK_MISSION_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "SAFWCARM"."ZONE" ("ID_ZONE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POUBELLE
--------------------------------------------------------

  ALTER TABLE "SAFWCARM"."POUBELLE" ADD CONSTRAINT "FK_POUBELLE_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "SAFWCARM"."ZONE" ("ID_ZONE") ON DELETE CASCADE ENABLE;
